Homework 1
bumashka/auto-tests_mariya-buldakova pull request #1
Opened 2023-04-16 19:40 UTC by bumashka

Что-то такое получилось

2023-04-19 17:46 UTC, Shukshin-test requested changes
Душил как мог

2023-04-19 17:46 UTC, Shukshin-test commented on src/test/java/homework1/IsPositiveTest.java
> +public class IsPositiveTest extends BeforeAllTests {
Убрать модификаторы доступа на тестовых классах и методах, см. https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods

2023-04-19 17:46 UTC, Shukshin-test commented on pom.xml
>        <groupId>com.local</groupId>
Вариант получше:
```
    <dependency>
      <groupId>com.epam.tat.module4</groupId>
      <artifactId>calculator</artifactId>
      <version>1.0</version>
      <scope>system</scope>
      <systemPath>${project.basedir}/calculator-1.0.jar</systemPath>
    </dependency>

```
но не критично

2023-04-19 17:46 UTC, Shukshin-test commented on pom.xml
>        <groupId>com.local</groupId>
Ещё почистить бы от лишних плагинов, вряд ли тот же deploy нужен

2023-04-19 17:46 UTC, Shukshin-test commented on src/test/java/homework1/BeforeAllTests.java
> +public class BeforeAllTests {
Из конвенции:

**/Test*.java           
**/*Test.java           
**/*Tests.java          
**/*TestCase.java       

паттерны для тест-классов, но тест класс должен включать тесты, так что надо бы изменить имя класса

2023-04-19 17:46 UTC, Shukshin-test commented on src/test/java/homework1/MultTest.java
> +public class MultTest extends BeforeAllTests{
https://www.jetbrains.com/idea/guide/tutorials/reformatting-code/reformatting-before-commit/ а то скобочки вплотную к буквам глаза режут

2023-04-19 17:46 UTC, Shukshin-test commented on src/test/java/homework1/BeforeAllTests.java
> +public class BeforeAllTests {
А ссылку на конвенцию съела собака

2023-04-20 13:57 UTC, bumashka commented
Вроде бы подправила. Насчёт плагинов, я просто боюсь убрать случайно нужное. А какие нам точно не нужны не понимаю.

2023-04-24 11:36 UTC, merged