Homework 3
bumashka/auto-tests_mariya-buldakova pull request #3
Opened 2023-04-25 00:53 UTC by bumashka

Что-то получилось

2023-05-17 18:04 UTC, Shukshin-test requested changes
Проще всего вместо "магических" чисел использовать енамы, типо такого https://www.baeldung.com/java-enum-values#adding-constructor

А по-сути работа около идеальная

2023-05-17 18:04 UTC, Shukshin-test commented on src/test/java/homework3/Driver.java
> +        System.setProperty("webdriver.chrome.driver", "C:\\test-app\\src\\test\\resources\\chromedriver.exe");
Надо сделать относительный путь

2023-05-17 18:04 UTC, Shukshin-test commented on src/test/java/homework3/pages/DifferentElements.java
> +                .substring(9)).collect(Collectors.toList());
magic number

2023-05-17 18:04 UTC, Shukshin-test commented on src/test/java/homework3/pages/DifferentElements.java
> +                .substring(9)).collect(Collectors.toList());
https://en.wikipedia.org/wiki/Magic_number_(programming)

2023-05-17 18:04 UTC, Shukshin-test commented on src/test/java/homework2/Ex2Test.java
> +        List<String> logs = webDriver.findElements(By.cssSelector("ul[class='panel-body-list logs'] > li")).stream().map((s) -> s.getText().substring(9)).collect(Collectors.toList());
magic number
https://en.wikipedia.org/wiki/Magic_number_(programming)

2023-05-19 15:51 UTC, bumashka commented
Подправила, энам добавлять не стала... Во второй домашке тоже подправила.

2023-05-26 10:25 UTC, Shukshin-test approved these changes

2023-05-28 11:12 UTC, merged